[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200

[theme]
primaryColor = "#2563EB"
base = "light"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"

[theme.sidebar]
primaryColor = "#38BDF8"
backgroundColor = "#0B132B"
secondaryBackgroundColor = "#111D3A"
textColor = "#DBEAFE"
